


-- List the number of films per category.
USE sakila;
SELECT
f.title,
c.name
FROM film_category AS fc
LEFT JOIN film AS f
ON fc.film_id = f.film_id
LEFT JOIN category AS c
ON fc.category_id = c.category_id;

-- Retrieve the store ID, city, and country for each store.

SELECT 
a.address
FROM store AS s
LEFT JOIN address AS a
ON s.address_id = a.address_id;

-- Calculate the total revenue generated by each store in dollars.
SELECT 
a.address,
SUM(p.amount) AS total_payment

FROM payment AS p
LEFT JOIN rental AS r
	ON p.rental_id = r.rental_id
LEFT JOIN staff AS s
	ON p.staff_id = s.staff_id
LEFT JOIN store AS st
	ON s.store_id = st.store_id
LEFT JOIN address AS a
	ON st.address_id = a.address_id
    
GROUP BY a.address_id;


-- Determine the average running time of films for each category

SELECT c.name AS category_name, 
       AVG(f.length) AS average_running_time
FROM film f
JOIN film_category fc ON f.film_id = fc.film_id
JOIN category c ON fc.category_id = c.category_id
GROUP BY c.name;







